name: lunya
description: Furry content aggregator.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  async_wallpaper: ^2.0.3
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  xml: ^6.5.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
