name: furry_content_hub
description: Furry content aggregator
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  cached_network_image: ^3.3.0
  video_player: ^2.8.1
  share_plus: ^7.2.1
  wallpaper_manager_flutter: ^0.0.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
