dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.2
  video_player: ^2.8.1

dev_dependencies:
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
