name: furry_content_hub
description: Furry content aggregator with parsing and filters.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  html: ^0.15.4
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  gallery_saver: ^2.3.2
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
