name: furry_content_hub
description: Furry wallpaper aggregator
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.10.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  webview_flutter: ^4.5.0
  html: ^0.15.4
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  path_provider: ^2.1.1
  workmanager: ^0.5.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
